// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using ConsoleApplication2.Models;
using Microsoft.Rest;

namespace ConsoleApplication2.Models
{
    public partial class AnimationCard
    {
        private bool? _autoloop;
        
        /// <summary>
        /// Optional. Should the client loop playback at end of content
        /// (default:true)
        /// </summary>
        public bool? Autoloop
        {
            get { return this._autoloop; }
            set { this._autoloop = value; }
        }
        
        private bool? _autostart;
        
        /// <summary>
        /// Optional. Should the client automatically start playback of video
        /// in this card (default:true)
        /// </summary>
        public bool? Autostart
        {
            get { return this._autostart; }
            set { this._autostart = value; }
        }
        
        private IList<CardAction> _buttons;
        
        /// <summary>
        /// Optional. Set of actions applicable to the current card
        /// </summary>
        public IList<CardAction> Buttons
        {
            get { return this._buttons; }
            set { this._buttons = value; }
        }
        
        private ThumbnailUrl _image;
        
        /// <summary>
        /// Optional. Thumbnail placeholder
        /// </summary>
        public ThumbnailUrl Image
        {
            get { return this._image; }
            set { this._image = value; }
        }
        
        private IList<MediaUrl> _media;
        
        /// <summary>
        /// Optional. Array of media Url objects
        /// </summary>
        public IList<MediaUrl> Media
        {
            get { return this._media; }
            set { this._media = value; }
        }
        
        private bool? _shareable;
        
        /// <summary>
        /// Optional. Is it OK for this content to be shareable with others
        /// (default:true)
        /// </summary>
        public bool? Shareable
        {
            get { return this._shareable; }
            set { this._shareable = value; }
        }
        
        private string _subtitle;
        
        /// <summary>
        /// Optional. Subtitle of the card
        /// </summary>
        public string Subtitle
        {
            get { return this._subtitle; }
            set { this._subtitle = value; }
        }
        
        private string _text;
        
        /// <summary>
        /// Optional. Text of the card
        /// </summary>
        public string Text
        {
            get { return this._text; }
            set { this._text = value; }
        }
        
        private string _title;
        
        /// <summary>
        /// Optional. Title of the card
        /// </summary>
        public string Title
        {
            get { return this._title; }
            set { this._title = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the AnimationCard class.
        /// </summary>
        public AnimationCard()
        {
            this.Buttons = new LazyList<CardAction>();
            this.Media = new LazyList<MediaUrl>();
        }
    }
}
