// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace ConsoleApplication2.Models
{
    public partial class Conversation
    {
        private string _conversationId;
        
        /// <summary>
        /// Optional. ID for this conversation
        /// </summary>
        public string ConversationId
        {
            get { return this._conversationId; }
            set { this._conversationId = value; }
        }
        
        private string _eTag;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ETag
        {
            get { return this._eTag; }
            set { this._eTag = value; }
        }
        
        private int? _expiresIN;
        
        /// <summary>
        /// Optional. Expiration for token
        /// </summary>
        public int? ExpiresIN
        {
            get { return this._expiresIN; }
            set { this._expiresIN = value; }
        }
        
        private string _streamUrl;
        
        /// <summary>
        /// Optional. URL for this conversation's message stream
        /// </summary>
        public string StreamUrl
        {
            get { return this._streamUrl; }
            set { this._streamUrl = value; }
        }
        
        private string _token;
        
        /// <summary>
        /// Optional. Token scoped to this conversation
        /// </summary>
        public string Token
        {
            get { return this._token; }
            set { this._token = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Conversation class.
        /// </summary>
        public Conversation()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken conversationIdValue = inputObject["conversationId"];
                if (conversationIdValue != null && conversationIdValue.Type != JTokenType.Null)
                {
                    this.ConversationId = ((string)conversationIdValue);
                }
                JToken eTagValue = inputObject["eTag"];
                if (eTagValue != null && eTagValue.Type != JTokenType.Null)
                {
                    this.ETag = ((string)eTagValue);
                }
                JToken expiresINValue = inputObject["expires_in"];
                if (expiresINValue != null && expiresINValue.Type != JTokenType.Null)
                {
                    this.ExpiresIN = ((int)expiresINValue);
                }
                JToken streamUrlValue = inputObject["streamUrl"];
                if (streamUrlValue != null && streamUrlValue.Type != JTokenType.Null)
                {
                    this.StreamUrl = ((string)streamUrlValue);
                }
                JToken tokenValue = inputObject["token"];
                if (tokenValue != null && tokenValue.Type != JTokenType.Null)
                {
                    this.Token = ((string)tokenValue);
                }
            }
        }
    }
}
