// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;

namespace ConsoleApplication2.Models
{
    public partial class Place
    {
        private string _address;
        
        /// <summary>
        /// Optional. Address of the place (may be `string` or complex object
        /// of type `PostalAddress`)
        /// </summary>
        public string Address
        {
            get { return this._address; }
            set { this._address = value; }
        }
        
        private string _geo;
        
        /// <summary>
        /// Optional. Geo coordinates of the place (may be complex object of
        /// type `GeoCoordinates` or `GeoShape`)
        /// </summary>
        public string Geo
        {
            get { return this._geo; }
            set { this._geo = value; }
        }
        
        private string _hasMap;
        
        /// <summary>
        /// Optional. Map to the place (may be `string` (URL) or complex object
        /// of type `Map`)
        /// </summary>
        public string HasMap
        {
            get { return this._hasMap; }
            set { this._hasMap = value; }
        }
        
        private string _name;
        
        /// <summary>
        /// Optional. The name of the thing
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set { this._name = value; }
        }
        
        private string _type;
        
        /// <summary>
        /// Optional. The type of the thing
        /// </summary>
        public string Type
        {
            get { return this._type; }
            set { this._type = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Place class.
        /// </summary>
        public Place()
        {
        }
    }
}
