// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using ConsoleApplication2.Models;
using Microsoft.Rest;

namespace ConsoleApplication2.Models
{
    public partial class ReceiptCard
    {
        private IList<CardAction> _buttons;
        
        /// <summary>
        /// Optional. Set of actions applicable to the current card
        /// </summary>
        public IList<CardAction> Buttons
        {
            get { return this._buttons; }
            set { this._buttons = value; }
        }
        
        private IList<Fact> _facts;
        
        /// <summary>
        /// Optional. Array of Fact Objects   Array of key-value pairs.
        /// </summary>
        public IList<Fact> Facts
        {
            get { return this._facts; }
            set { this._facts = value; }
        }
        
        private IList<ReceiptItem> _items;
        
        /// <summary>
        /// Optional. Array of Receipt Items
        /// </summary>
        public IList<ReceiptItem> Items
        {
            get { return this._items; }
            set { this._items = value; }
        }
        
        private CardAction _tap;
        
        /// <summary>
        /// Optional. This action will be activated when user taps on the card
        /// </summary>
        public CardAction Tap
        {
            get { return this._tap; }
            set { this._tap = value; }
        }
        
        private string _tax;
        
        /// <summary>
        /// Optional. Total amount of TAX paid(or should be paid)
        /// </summary>
        public string Tax
        {
            get { return this._tax; }
            set { this._tax = value; }
        }
        
        private string _title;
        
        /// <summary>
        /// Optional. Title of the card
        /// </summary>
        public string Title
        {
            get { return this._title; }
            set { this._title = value; }
        }
        
        private string _total;
        
        /// <summary>
        /// Optional. Total amount of money paid (or should be paid)
        /// </summary>
        public string Total
        {
            get { return this._total; }
            set { this._total = value; }
        }
        
        private string _vat;
        
        /// <summary>
        /// Optional. Total amount of VAT paid(or should be paid)
        /// </summary>
        public string Vat
        {
            get { return this._vat; }
            set { this._vat = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ReceiptCard class.
        /// </summary>
        public ReceiptCard()
        {
            this.Buttons = new LazyList<CardAction>();
            this.Facts = new LazyList<Fact>();
            this.Items = new LazyList<ReceiptItem>();
        }
    }
}
