// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using ConsoleApplication2.Models;
using Microsoft.Rest;

namespace ConsoleApplication2.Models
{
    public partial class SigninCard
    {
        private IList<CardAction> _buttons;
        
        /// <summary>
        /// Optional. Action to use to perform signin
        /// </summary>
        public IList<CardAction> Buttons
        {
            get { return this._buttons; }
            set { this._buttons = value; }
        }
        
        private string _text;
        
        /// <summary>
        /// Optional. Text for signin request
        /// </summary>
        public string Text
        {
            get { return this._text; }
            set { this._text = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the SigninCard class.
        /// </summary>
        public SigninCard()
        {
            this.Buttons = new LazyList<CardAction>();
        }
    }
}
