// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Net.Http;
using ConsoleApplication2;
using Microsoft.Rest;

namespace ConsoleApplication2
{
    public partial class BotConnectorDirectLineAPIV30 : ServiceClient<BotConnectorDirectLineAPIV30>, IBotConnectorDirectLineAPIV30
    {
        private Uri _baseUri;
        
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        public Uri BaseUri
        {
            get { return this._baseUri; }
            set { this._baseUri = value; }
        }
        
        private ServiceClientCredentials _credentials;
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        public ServiceClientCredentials Credentials
        {
            get { return this._credentials; }
            set { this._credentials = value; }
        }
        
        private IConversations _conversations;
        
        public virtual IConversations Conversations
        {
            get { return this._conversations; }
        }
        
        private ITokens _tokens;
        
        public virtual ITokens Tokens
        {
            get { return this._tokens; }
        }
        
        /// <summary>
        /// Initializes a new instance of the BotConnectorDirectLineAPIV30
        /// class.
        /// </summary>
        public BotConnectorDirectLineAPIV30()
            : base()
        {
            this._conversations = new Conversations(this);
            this._tokens = new Tokens(this);
            this._baseUri = new Uri("https://directline.botframework.com");
        }
        
        /// <summary>
        /// Initializes a new instance of the BotConnectorDirectLineAPIV30
        /// class.
        /// </summary>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public BotConnectorDirectLineAPIV30(params DelegatingHandler[] handlers)
            : base(handlers)
        {
            this._conversations = new Conversations(this);
            this._tokens = new Tokens(this);
            this._baseUri = new Uri("https://directline.botframework.com");
        }
        
        /// <summary>
        /// Initializes a new instance of the BotConnectorDirectLineAPIV30
        /// class.
        /// </summary>
        /// <param name='rootHandler'>
        /// Optional. The http client handler used to handle http transport.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public BotConnectorDirectLineAPIV30(HttpClientHandler rootHandler, params DelegatingHandler[] handlers)
            : base(rootHandler, handlers)
        {
            this._conversations = new Conversations(this);
            this._tokens = new Tokens(this);
            this._baseUri = new Uri("https://directline.botframework.com");
        }
        
        /// <summary>
        /// Initializes a new instance of the BotConnectorDirectLineAPIV30
        /// class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public BotConnectorDirectLineAPIV30(Uri baseUri, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            this._baseUri = baseUri;
        }
        
        /// <summary>
        /// Initializes a new instance of the BotConnectorDirectLineAPIV30
        /// class.
        /// </summary>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public BotConnectorDirectLineAPIV30(ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
        
        /// <summary>
        /// Initializes a new instance of the BotConnectorDirectLineAPIV30
        /// class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public BotConnectorDirectLineAPIV30(Uri baseUri, ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._baseUri = baseUri;
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
    }
}
