// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using ConsoleApplication2.Models;

namespace ConsoleApplication2.Models
{
    public partial class CardImage
    {
        private string _alt;
        
        /// <summary>
        /// Optional. Image description intended for screen readers
        /// </summary>
        public string Alt
        {
            get { return this._alt; }
            set { this._alt = value; }
        }
        
        private CardAction _tap;
        
        /// <summary>
        /// Optional. Action assigned to specific Attachment.E.g.navigate to
        /// specific URL or play/open media content
        /// </summary>
        public CardAction Tap
        {
            get { return this._tap; }
            set { this._tap = value; }
        }
        
        private string _url;
        
        /// <summary>
        /// Optional. URL Thumbnail image for major content property.
        /// </summary>
        public string Url
        {
            get { return this._url; }
            set { this._url = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the CardImage class.
        /// </summary>
        public CardImage()
        {
        }
    }
}
