// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using ConsoleApplication2.Models;

namespace ConsoleApplication2.Models
{
    public partial class Mention
    {
        private ChannelAccount _mentioned;
        
        /// <summary>
        /// Optional. The mentioned user
        /// </summary>
        public ChannelAccount Mentioned
        {
            get { return this._mentioned; }
            set { this._mentioned = value; }
        }
        
        private string _text;
        
        /// <summary>
        /// Optional. Sub Text which represents the mention (can be null or
        /// empty)
        /// </summary>
        public string Text
        {
            get { return this._text; }
            set { this._text = value; }
        }
        
        private string _type;
        
        /// <summary>
        /// Optional. Entity Type (typically from schema.org types)
        /// </summary>
        public string Type
        {
            get { return this._type; }
            set { this._type = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Mention class.
        /// </summary>
        public Mention()
        {
        }
    }
}
