// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using ConsoleApplication2.Models;

namespace ConsoleApplication2.Models
{
    public partial class ReceiptItem
    {
        private CardImage _image;
        
        /// <summary>
        /// Optional. Image
        /// </summary>
        public CardImage Image
        {
            get { return this._image; }
            set { this._image = value; }
        }
        
        private string _price;
        
        /// <summary>
        /// Optional. Amount with currency
        /// </summary>
        public string Price
        {
            get { return this._price; }
            set { this._price = value; }
        }
        
        private string _quantity;
        
        /// <summary>
        /// Optional. Number of items of given kind
        /// </summary>
        public string Quantity
        {
            get { return this._quantity; }
            set { this._quantity = value; }
        }
        
        private string _subtitle;
        
        /// <summary>
        /// Optional. Subtitle appears just below Title field, differs from
        /// Title in font styling only
        /// </summary>
        public string Subtitle
        {
            get { return this._subtitle; }
            set { this._subtitle = value; }
        }
        
        private CardAction _tap;
        
        /// <summary>
        /// Optional. This action will be activated when user taps on the Item
        /// bubble.
        /// </summary>
        public CardAction Tap
        {
            get { return this._tap; }
            set { this._tap = value; }
        }
        
        private string _text;
        
        /// <summary>
        /// Optional. Text field appears just below subtitle, differs from
        /// Subtitle in font styling only
        /// </summary>
        public string Text
        {
            get { return this._text; }
            set { this._text = value; }
        }
        
        private string _title;
        
        /// <summary>
        /// Optional. Title of the Card
        /// </summary>
        public string Title
        {
            get { return this._title; }
            set { this._title = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ReceiptItem class.
        /// </summary>
        public ReceiptItem()
        {
        }
    }
}
