// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;

namespace ConsoleApplication2.Models
{
    public partial class ThumbnailUrl
    {
        private string _alt;
        
        /// <summary>
        /// Optional. Alt text to display for screen readers on the thumbnail
        /// image
        /// </summary>
        public string Alt
        {
            get { return this._alt; }
            set { this._alt = value; }
        }
        
        private string _url;
        
        /// <summary>
        /// Optional. url pointing to an thumbnail to use for media content
        /// </summary>
        public string Url
        {
            get { return this._url; }
            set { this._url = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ThumbnailUrl class.
        /// </summary>
        public ThumbnailUrl()
        {
        }
    }
}
