// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using ConsoleApplication2.Models;
using Microsoft.Rest;

namespace ConsoleApplication2.Models
{
    public partial class ThumbnailCard
    {
        private IList<CardAction> _buttons;
        
        /// <summary>
        /// Optional. Set of actions applicable to the current card
        /// </summary>
        public IList<CardAction> Buttons
        {
            get { return this._buttons; }
            set { this._buttons = value; }
        }
        
        private IList<CardImage> _images;
        
        /// <summary>
        /// Optional. Array of images for the card
        /// </summary>
        public IList<CardImage> Images
        {
            get { return this._images; }
            set { this._images = value; }
        }
        
        private string _subtitle;
        
        /// <summary>
        /// Optional. Subtitle of the card
        /// </summary>
        public string Subtitle
        {
            get { return this._subtitle; }
            set { this._subtitle = value; }
        }
        
        private CardAction _tap;
        
        /// <summary>
        /// Optional. This action will be activated when user taps on the card
        /// itself
        /// </summary>
        public CardAction Tap
        {
            get { return this._tap; }
            set { this._tap = value; }
        }
        
        private string _text;
        
        /// <summary>
        /// Optional. Text for the card
        /// </summary>
        public string Text
        {
            get { return this._text; }
            set { this._text = value; }
        }
        
        private string _title;
        
        /// <summary>
        /// Optional. Title of the card
        /// </summary>
        public string Title
        {
            get { return this._title; }
            set { this._title = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ThumbnailCard class.
        /// </summary>
        public ThumbnailCard()
        {
            this.Buttons = new LazyList<CardAction>();
            this.Images = new LazyList<CardImage>();
        }
    }
}
